apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraweb
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraweb
  template:
    metadata:
      labels:
        app: infraweb
    spec:
      containers:
        - name: infraweb
          image: dockerhub/infraweb:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: infraweb
  namespace: app
spec:
  selector:
    app: infraweb
  ports:
    - port: 80
      targetPort: 80
